### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by jcjrobert** [RafuiiChan/nonebot_plugin_miragetank#1]
每次生成都有这个警告，在np.where那里
虽然排除了0，但是依然还有nan值没有排除
但问题是排除了就会显示The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

等一波解决

**Comment by jcjrobert** [comment]
虽然这个警告并不影响生成就是了

**Comment by 1umine** [comment]
> 每次生成都有这个警告，在np.where那里 虽然排除了0，但是依然还有nan值没有排除 但问题是排除了就会显示The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> 
> 等一波解决

啊这，一直没注意过，看了下确实有这个问题，不过核心算法是搬别人的，我也没仔细研究过，不太懂这个。（蹲个大佬解决）
~~总之能用就行~~

**Comment by 1umine** [comment]
在`data_source.py`前面加句这个就没有这个警告了

`np.seterr(divide='ignore',invalid='ignore')`


~~（只要我看不到有报错并且不影响运行结果就当他不存在好了x）~~
