### ISSUE TITLE
关于此插件在 nonebot 2.0.0.rc1 报错反馈

### ISSUE THREAD

**Issue by Voice-of-Shadow** [RafuiiChan/nonebot_plugin_miragetank#2]
可能由于官方的破坏性更新——移除过时的 State 注入参数
导致加载插件时报错
删除和修改State注入参数后。没有任何反应

**Comment by 1umine** [comment]
> 可能由于官方的破坏性更新——移除过时的 State 注入参数 导致加载插件时报错 删除和修改State注入参数后。没有任何反应

`from nonebot.params import CommandArg, State` 的State删掉，

`state: T_State = State()` 改为 `state: T_State`

是这么改的吗？

**Comment by 1umine** [comment]
> > 可能由于官方的破坏性更新——移除过时的 State 注入参数 导致加载插件时报错 删除和修改State注入参数后。没有任何反应
> 
> `from nonebot.params import CommandArg, State` 的State删掉，
> 
> `state: T_State = State()` 改为 `state: T_State`
> 
> 是这么改的吗？

自己换了个rc环境，这样改了下，运行正常

**Comment by Voice-of-Shadow** [comment]
对、我也是这样更改的。运行不起来发现我是笨比。init中指令是 '生成幻影坦克'。我测试时候一直用 '幻影坦克' 命令 ……没仔细看源文件。作者可以更改一下 readme 中的 "命令"。
然后根据测试发现他无法接收用户上传的图片进行合成。或许此项可以作为后续优化的方向~

**Comment by 1umine** [comment]
> 对、我也是这样更改的。运行不起来发现我是笨比。init中指令是 '生成幻影坦克'。我测试时候一直用 '幻影坦克' 命令 ……没仔细看源文件。作者可以更改一下 readme 中的 "命令"。 然后根据测试发现他无法接收用户上传的图片进行合成。或许此项可以作为后续优化的方向~

命令名称问题可以 aliases 里加个 `幻影坦克`，无法接收用户上传的图片进行合成详细描述一下，有截图更好，目前我测试的正常情况下是可以
```
A: /生成幻影坦克 color
Bot: 发送一张图片
A: 图片1
Bot: 还要一张
A: 图片2
Bot: 开始合成
Bot: [合成图]
```
也可以
```
A: /生成幻影坦克 color [图片1] [图片2]
Bot: 开始合成
Bot: [合成图]
```

**Comment by Voice-of-Shadow** [comment]
就是不处理用户通过文件上传的图片。它直接没有反应。通过截图或者复制的复制的方式才会处理消息。
`>生成幻影坦克 color [上传的图片文件1] [上传的图片文件2]`
![QQ截图20221008182357](https://user-images.githubusercontent.com/115323324/194702897-ec10fe73-8f57-4e44-8c5d-03bb3eac31f4.png)

**Comment by 1umine** [comment]
> 就是不处理用户通过文件上传的图片。它直接没有反应。通过截图或者复制的复制的方式才会处理消息。 `>生成幻影坦克 color [上传的图片文件1] [上传的图片文件2]` ![QQ截图20221008182357](https://user-images.githubusercontent.com/115323324/194702897-ec10fe73-8f57-4e44-8c5d-03bb3eac31f4.png)

感觉有点难搞，跨事件会话了（~~等个有缘人PR~~）
