### ISSUE TITLE
关于此插件功能附加建议、

### ISSUE THREAD

**Issue by Voice-of-Shadow** [RafuiiChan/nonebot_plugin_miragetank#3]
作者在未来的版本更新中可以添加幻影坦克分离功能。
将表里作为参数记录、

<del>咱有空研究()</del>

**Comment by 1umine** [comment]
加了，不过分离效果堪忧（本来合成的效果感觉也不是很完美）。
在没有原图的情况下从合成好的图里分离出两张原图目前感觉应该做不到（）

**Comment by Voice-of-Shadow** [comment]
嗯、因为处理的图就是砍掉了颜色信息、原理倒是知道、肯定无法逆向的。
只是或许可以让PC端用户有个好一点儿的体验、不用移除来放到黑色背景里去查看。
自动处理叠方便查看。或者也方便群友们搜图<del>作者更新神速已长跪、、</del>
