### ISSUE TITLE
在zhenxunbot中使用下载图片失败

### ISSUE THREAD

**Issue by xingyu42** [RafuiiChan/nonebot_plugin_miragetank#4]
![image](https://github.com/1umine/nonebot_plugin_miragetank/assets/52421598/8eeb37e3-608c-4224-b7d2-4d2b4830f7c2)
03-30 15:20:03 [SUCCESS] nonebot | OneBot V11 2769068180 | [message.private.friend]: Message -2147481917 from 1294266616 '生成幻影坦克 gray'

03-30 15:20:03 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.nonebot_plugin_miragetank)

03-30 15:20:03 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.nonebot_plugin_miragetank) running complete

03-30 15:20:06 [SUCCESS] nonebot | OneBot V11 2769068180 | [message.private.friend]: Message -2147481915 from 1294266616 '[image:file=A26D44C7E01A581F8F3056465ECAFB0E.jpg,url=https://gchat.qpic.cn/download?appid=1406&fileid=CgoxMjk0MjY2NjE2Eh...,file_size=277209]'

03-30 15:20:06 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.nonebot_plugin_miragetank)

03-30 15:20:10 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.nonebot_plugin_miragetank)

03-30 15:20:11 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.nonebot_plugin_miragetank) running complete

03-30 15:20:10 [SUCCESS] nonebot | OneBot V11 2769068180 | [message.private.friend]: Message -2147481913 from 1294266616 '[image:file=85FD71D0C1A5E9C7A83511BE5CD6F6AC.jpg,url=https://gchat.qpic.cn/download?appid=1406&fileid=CgoxMjk0MjY2NjE2Eh...,file_size=202358]'

03-30 15:20:07 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.nonebot_plugin_miragetank) running complete
![image](https://github.com/1umine/nonebot_plugin_miragetank/assets/52421598/854446b2-daa5-4142-94e8-e07aaaf9d1bc)

**Comment by 1umine** [comment]
试试能不能直接访问图片URL，到协议端（比如gocq）日志找到对应消息，复制图片URL到浏览器打开，注意可能 & 会被转义

**Comment by xingyu42** [comment]
,"raw_message":"[CQ:image,file=022C9D95109D7023BE218858BB8E30E8.jpg,url=https://gchat.qpic.cn/download?appid=1407&amp;fileid=CgoxMjk0MjY2NjE2EhR7IlxixS69oFA7uAYBh5a0BSqv2Bj50xAg_gooi7LMkcObhQNQgLsv&amp;rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&amp;spec=0,file_size=272889]","font":14,"sub_type":"friend","message":[{"data":{"file":"022C9D95109D7023BE218858BB8E30E8.jpg","url":"https://gchat.qpic.cn/download?appid=1407&fileid=CgoxMjk0MjY2NjE2EhR7IlxixS69oFA7uAYBh5a0BSqv2Bj50xAg_gooi7LMkcObhQNQgLsv&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&spec=0","file_size":"272889"},"type":"image"}],"message_format":"array","post_type":"message"} 
看上去不能访问不知道是不是，只有这个了

**Comment by 1umine** [comment]
图片似乎404了

**Comment by xingyu42** [comment]
> 图片似乎404了

我用llonebot当协议端[https://github.com/LLOneBot/LLOneBot](url)，不知道有没有问题

**Comment by 1umine** [comment]
不太清楚，但是这个URL看着好像不太对劲的样子，一般私聊发的图域名是 c2cpicdw 的，这个是 gchat ，群聊一般是这个

**Comment by xingyu42** [comment]
bot自带有上传图库功能这可以正常获取图片，可能插件获取url有问题吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月30日(周六) 下午4:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1umine/nonebot_plugin_miragetank] 在zhenxunbot中使用下载图片失败 (Issue #4)




 
不太清楚，但是这个URL看着好像不太对劲的样子，一般私聊发的图域名是 c2cpicdw 的，这个是 gchat ，群聊一般是这个

**Comment by 1umine** [comment]
> bot自带有上传图库功能这可以正常获取图片，可能插件获取url有问题吧

可以试试找到插件源码，在 `data_source.py` 第 157 行前面加一行 `print(img_urls)` 看看插件获取到的 url 是不是正常的

**Comment by xingyu42** [comment]
> > bot自带有上传图库功能这可以正常获取图片，可能插件获取url有问题吧
> 
> 可以试试找到插件源码，在 `data_source.py` 第 157 行前面加一行 `print(img_urls)` 看看插件获取到的 url 是不是正常的

![image](https://github.com/1umine/nonebot_plugin_miragetank/assets/52421598/beaa856d-ac85-494b-8237-7ec66a42f5cb)
出现这个
['https://gchat.qpic.cn/download?appid=1407&fileid=CgoxMjk0MjY2NjE2EhR7IlxixS69oFA7uAYBh5a0BSqv2Bj50xAg_goo9LDq5embhQNQgLsv&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&spec=0', 'https://gchat.qpic.cn/download?appid=1407&fileid=CgoxMjk0MjY2NjE2EhR7IlxixS69oFA7uAYBh5a0BSqv2Bj50xAg_gook6Ps6embhQNQgLsv&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&spec=0']

**Comment by 1umine** [comment]
可以看看上传图库的代码吗, 这个链接获取应该没问题，就是上报的链接，或者把上传图库过程中的下载图片部分的链接也打印出来对比一下

**Comment by xingyu42** [comment]
> 可以看看上传图库的代码吗, 这个链接获取应该没问题，就是上报的链接，或者把上传图库过程中的下载图片部分的链接也打印出来对比一下

[upload_image.zip](https://github.com/1umine/nonebot_plugin_miragetank/files/14811683/upload_image.zip)
源码和些可能用到的依赖文件

**Comment by 1umine** [comment]
怪，获取图片url方法是一样的，获取到的链接应该是一样的，一个能用应该都能用的，无 referer 访问应该也不会404而是显示不可引用的图（）

**Comment by xingyu42** [comment]
> 怪，获取图片url方法是一样的，获取到的链接应该是一样的，一个能用应该都能用的，无 referer 访问应该也不会404而是显示不可引用的图（）

确实之前我有尝试调用那个来下载也是一样，这就不知道怎么搞了，依赖和py版本都没问题，想不明白了
![0010CDE1](https://github.com/1umine/nonebot_plugin_miragetank/assets/52421598/a204095e-8d21-4da7-bde3-069b13948fd7)

**Comment by 1umine** [comment]
那大概是QQ的问题了，图片URL失效，跟py没啥关系，可以多尝试一些其他情况，按理来说能正常访问就能下载

**Comment by xingyu42** [comment]
但是其他能，就这不行真是太奇怪了🧐



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月30日(周六) 晚上10:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1umine/nonebot_plugin_miragetank] 在zhenxunbot中使用下载图片失败 (Issue #4)




 
那大概是QQ的问题了，图片URL失效，跟py没啥关系

**Comment by xingyu42** [comment]
问题解决换其他适配器就好了
