### ISSUE TITLE
bug？

### ISSUE THREAD

**Issue by D-6CF-X** [RafuiiChan/nonebot_plugin_miragetank#6]
![image](https://github.com/user-attachments/assets/d329034e-1981-41f0-a25b-4e5d01beeb75)
使用gray合成时报的错color也报错
![image](https://github.com/user-attachments/assets/34019827-5fdf-4343-aebd-d5b07cda3499)

**Comment by 1umine** [comment]
httpx（上游）问题，降级httpx或许能解决，参考

https://github.com/1umine/nonebot_plugin_charpic/issues/3

**Comment by D-6CF-X** [comment]
![image](https://github.com/user-attachments/assets/1042fc22-d20a-43e2-915e-d38c2fe8d5c8)
httpx==0.25.1依旧报错

**Comment by 1umine** [comment]
> ![image](https://github.com/user-attachments/assets/1042fc22-d20a-43e2-915e-d38c2fe8d5c8)
> httpx==0.25.1依旧报错

我自己用着好像没啥问题，这个是ntqq图片域名的ssl问题，参考 https://github.com/LagrangeDev/Lagrange.Core/issues/315

需要改一下ssl context，~~暂时不太想搞，等pr（~~

**Comment by D-6CF-X** [comment]
![image](https://github.com/user-attachments/assets/4b9eb653-4d5c-491d-82df-4a9221a50260)
emm塞哪里，没塞过

**Comment by 1umine** [comment]
> ![image](https://github.com/user-attachments/assets/4b9eb653-4d5c-491d-82df-4a9221a50260)
> emm塞哪里，没塞过

塞到client.get上面一行

**Comment by D-6CF-X** [comment]
![Uploading image.png…]()

**Comment by D-6CF-X** [comment]
![image](https://github.com/user-attachments/assets/4d831f49-d7af-403d-9380-03ecf90a6e40)
报错了直接

**Comment by 1umine** [comment]
缩进没对齐

**Comment by D-6CF-X** [comment]
![image](https://github.com/user-attachments/assets/2c79a1eb-b2b3-4f7c-b862-8c09329c9ad9)
我还有什么没加吗

**Comment by 1umine** [comment]
更新了一下，改成 https://github.com/1umine/nonebot_plugin_miragetank/blob/main/nonebot_plugin_miragetank/data_source.py
试试

**Comment by D-6CF-X** [comment]
把py文件copy了一下解决了，可以正常使用了
